### ISSUE TITLE
Alpine cannot detect littleBIGtable

### ISSUE THREAD

**Issue by bhavya-tech** [indgy/LittleBigTable#2]
I have been recently trying to integrate littlebigtable in my website. However, alpinejs can't seem to detect the function in x-data. Below is the error in console.

Uncaught ReferenceError: littleBIGtable is not defined
    at eval (eval at d.el (alpine.js:144), <anonymous>:3:36)
    at d.el (alpine.js:144)
    at d (alpine.js:131)
    at f (alpine.js:139)
    at new be (alpine.js:1461)
    at Object.initializeComponent (alpine.js:1911)
    at alpine.js:1856
    at alpine.js:1870
    at NodeList.forEach (<anonymous>)
    at Object.discoverComponents (alpine.js:1869)

Alpine Error: "ReferenceError: littleBIGtable is not defined"
Expression: "littleBIGtable(options)"
Element: <div x-data=​"littleBIGtable(options)​" x-init=​"init()​">​…​</div>​<div class=​"level">​…​</div>​<div class=​"bg-white shadow-md rounded-xl my-6 overflow-auto">​…​</div>​<div class=​"level">​…​</div>​</div>​
u @ alpine.js:115
d @ alpine.js:134
f @ alpine.js:139
be @ alpine.js:1461
initializeComponent @ alpine.js:1911
(anonymous) @ alpine.js:1856
(anonymous) @ alpine.js:1870
discoverComponents @ alpine.js:1869
start @ alpine.js:1855
async function (async)
start @ alpine.js:59
(anonymous) @ alpine.js:1943
(anonymous) @ alpine.js:4
(anonymous) @ alpine.js:1

**Comment by defulmere** [comment]
I've been fighting with this issue myself. I believe that it is a problem with the version of LBT that the CDN is serving.

For example:

- The included examples work if you use the bundled `dist/littleBIGtable.min.js`
- The included examples work if you use the full un-minified `src/LittleBigTable.js`
- The included examples fail with `littleBIGtable is not defined` if you use the CDN version https://unpkg.com/littlebigtable@0.1.1/dist/littleBIGtable.min.js that's mentioned in the project README.

For now I'm working around the problem by using the bundled version instead of the CDN version.

**Comment by defulmere** [comment]
Actually after playing with this a bit more, I think the problem is due to the `defer` attribute in the CDN example on the project README:

```
<script src="https://unpkg.com/littlebigtable@0.1.1/dist/littleBIGtable.min.js" defer></script>
```

If I remove that attribute like so...

```
<script src="https://unpkg.com/littlebigtable@0.1.1/dist/littleBIGtable.min.js"></script>
```

... then I'm able to use the CDN version with no problem.

**Comment by defulmere** [comment]
Actually after playing with this a bit more I think the problem is related to the `defer` attribute on the CDN example in the project README:

```
<script src="https://unpkg.com/littlebigtable@0.1.1/dist/littleBIGtable.min.js" defer></script>
```

If I remove that attribute like so...

```
<script src="https://unpkg.com/littlebigtable@0.1.1/dist/littleBIGtable.min.js"></script>
```

... then my tables work correctly.

**Comment by indgy** [comment]
@bhavya-tech I think there may be an issue with the naming of littleBIGtable as I changed the case, I have updated the documentation which is now viewable here [https://littlebigtable.indgy.uk](https://littlebigtable.indgy.uk) Please check the examples and use the code there as the basis for your code.

@defulmere Thank you for taking the time to figure that out. I have updated the documentation to remove defer from the littleBIGtable script tag.
